#########################
## Sass Lint File
## See rules https://github.com/sasstools/sass-lint/tree/master/docs/rules
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.*'
# Rule Configuration
rules:
  attribute-quotes:
    - 2
    -
      include: true
  class-name-format:
    - 2
    - 
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  declarations-before-nesting:
    - 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-trailing-zero: 2
  no-trailing-whitespace: 2

  leading-zero:
    - 2
    -
      include: false
  no-vendor-prefixes:
    - 2
    -
      ignore-non-standard: true
  no-important: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 0
    -
      order: 'alphabetical'
      ignore-custom-properties: true
  property-units:
    - 1
    -
      global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
  quotes: 2
  space-after-colon: 2
  space-after-comma: 2
  single-line-per-selector: 2
  trailing-semicolon: 2
  variable-for-property:
    - 0
    -
      properties:
        - color
  zero-unit: 2
